apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/papoyan/playground.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: playground
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
