apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
spec:
  replicas: 1000
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: playground-app
  template:
    metadata:
      labels:
        app: playground-app
    spec:
      containers:
      - image: finallyzara/webapp:3.4
        name: playground-app
        ports:
        - containerPort: 80
